services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "4096M"
      MOTD: "Join the Discord! https://discord.steyaert.xyz"
      USE_AIKAR_FLAGS: "true"
      TZ: "America/New_York"
      DIFFICULTY: "2"
      ENABLE_COMMAND_BLOCK: "true"
      SPAWN_PROTECTION: "0"
      OPS: |-
        Steyaertc23
        THEREALPRO3K
      EXISTING_OPS_FILE: "SYNCHRONIZE"
      WHITELIST: |-
        Steyaertc23
        THEREALPRO3K
      EXISTING_WHITELIST_FILE: "SYNCHRONIZE"
      MODRINTH_PROJECTS: |
        worldedit
        worldguard
        autotreechop
        griefprevention
      PLAYER_IDLE_TIMEOUT: "15"
      BUG_REPORT_LINK: "https://forms.steyaert.xyz/reports/"
      SERVER_NAME: "SteyaertSMP"
      REPLACE_ENV_DURING_SYNC: "true"
      DISCORDSRV_BOT_TOKEN: "${DISCORDSRV_BOT_TOKEN}"
    volumes:
      - "./data:/data"
      # - "./plugins:/plugins" # CP THAT OVER
      # - "./configs:/data/config" # CP That over
    restart: unless-stopped

  forms:
    image: steyaertc23/forms:latest
    env_file:
        - .env.prod
    environment:
      - VIRTUAL_HOST=forms.steyaert.xyz
      - VIRTUAL_PORT=8000
    volumes:
      - "./database:/app/database"
    restart: unless-stopped
    init: true
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
