# Generated by Django 6.0.5 on 2026-05-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
